language: python

python:
  - 2.7

before_install:
  - sudo apt-get install libboost-dev

# command to install dependencies
# install: "pip install -r requirements.txt"

# script
script:
  - python -m unittest discover test

# turn of notifications
notifications:
  email: false

